**Personalised Medicine Recommending System**

In [10]:
import numpy as np
import pandas as pd 


In [11]:

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [12]:
med = pd.read_csv('/content/medicine dataset.txt')

In [13]:
med.isnull().sum()

index          0
Drug_Name      0
Reason         0
Description    0
dtype: int64

In [17]:
med.shape

(9720, 5)

In [18]:
med.head()

index                                          Drug_Name Reason  \
0      1               A CN Gel(Topical) 20gmA CN Soap 75gm   Acne   
1      2  A Ret 0.05% Gel 20gmA Ret 0.1% Gel 20gmA Ret 0...   Acne   
2      3                             ACGEL CL NANO Gel 15gm   Acne   
3      4                                ACGEL NANO Gel 15gm   Acne   
4      5                              Acleen 1% Lotion 25ml   Acne   

                                         Description  \
0                      Mild to moderate acne (spots)   
1  A RET 0.025% is a prescription medicine that i...   
2  It is used to treat acne vulgaris in people 12...   
3  It is used to treat acne vulgaris in people 12...   
4  treat the most severe form of acne (nodular ac...   

                                                tags  
0                  Mild to moderate acne (spots)Acne  
1  A RET 0.025% is a prescription medicine that i...  
2  It is used to treat acne vulgaris in people 12...  
3  It is used to treat acne vulgaris in people 12...  
4  treat the most severe form of acne (nodular ac...

In [19]:
med.dropna(inplace=False)

index                                          Drug_Name Reason  \
0         1               A CN Gel(Topical) 20gmA CN Soap 75gm   Acne   
1         2  A Ret 0.05% Gel 20gmA Ret 0.1% Gel 20gmA Ret 0...   Acne   
2         3                             ACGEL CL NANO Gel 15gm   Acne   
3         4                                ACGEL NANO Gel 15gm   Acne   
4         5                              Acleen 1% Lotion 25ml   Acne   
...     ...                                                ...    ...   
9715   9716                                T Muce Ointment 5gm  Wound   
9716   9717  Wokadine 10% Solution 100mlWokadine Solution 5...  Wound   
9717   9718                               Wokadine M Onit 10gm  Wound   
9718   9719                           Wound Fix Solution 100ml  Wound   
9719   9720                              Wounsol Ointment 15gm  Wound   

                                            Description  \
0                         Mild to moderate acne (spots)   
1     A RET 0.025% is a prescription medicine that i...   
2     It is used to treat acne vulgaris in people 12...   
3     It is used to treat acne vulgaris in people 12...   
4     treat the most severe form of acne (nodular ac...   
...                                                 ...   
9715                            used for treating warts   
9716                      used to soften the skin cells   
9717                                     used for scars   
9718                                    used for wounds   
9719  used to treat and remove raised warts (usually...   

                                                   tags  
0                     Mild to moderate acne (spots)Acne  
1     A RET 0.025% is a prescription medicine that i...  
2     It is used to treat acne vulgaris in people 12...  
3     It is used to treat acne vulgaris in people 12...  
4     treat the most severe form of acne (nodular ac...  
...                                                 ...  
9715                       used for treating wartsWound  
9716                 used to soften the skin cellsWound  
9717                                used for scarsWound  
9718                               used for woundsWound  
9719  used to treat and remove raised warts (usually...  

[9720 rows x 5 columns]

In [20]:
med.dropna(inplace=True)

In [21]:
med['Description']

0                           Mild to moderate acne (spots)
1       A RET 0.025% is a prescription medicine that i...
2       It is used to treat acne vulgaris in people 12...
3       It is used to treat acne vulgaris in people 12...
4       treat the most severe form of acne (nodular ac...
                              ...                        
9715                              used for treating warts
9716                        used to soften the skin cells
9717                                       used for scars
9718                                      used for wounds
9719    used to treat and remove raised warts (usually...
Name: Description, Length: 9720, dtype: object

In [22]:
med.duplicated().sum()

0

In [23]:
med['Description']

0                           Mild to moderate acne (spots)
1       A RET 0.025% is a prescription medicine that i...
2       It is used to treat acne vulgaris in people 12...
3       It is used to treat acne vulgaris in people 12...
4       treat the most severe form of acne (nodular ac...
                              ...                        
9715                              used for treating warts
9716                        used to soften the skin cells
9717                                       used for scars
9718                                      used for wounds
9719    used to treat and remove raised warts (usually...
Name: Description, Length: 9720, dtype: object

In [24]:
med['Description'].apply(lambda x:x.split())

0                     [Mild, to, moderate, acne, (spots)]
1       [A, RET, 0.025%, is, a, prescription, medicine...
2       [It, is, used, to, treat, acne, vulgaris, in, ...
3       [It, is, used, to, treat, acne, vulgaris, in, ...
4       [treat, the, most, severe, form, of, acne, (no...
                              ...                        
9715                         [used, for, treating, warts]
9716                 [used, to, soften, the, skin, cells]
9717                                   [used, for, scars]
9718                                  [used, for, wounds]
9719    [used, to, treat, and, remove, raised, warts, ...
Name: Description, Length: 9720, dtype: object

In [25]:
med['Reason'] = med['Reason'].apply(lambda x:x.split())
med['Description'] = med['Description'].apply(lambda x:x.split())

In [26]:
med['Description'] = med['Description'].apply(lambda x:[i.replace(" ","") for i in x])

In [27]:
med['tags'] = med['Description'] + med['Reason'] 

In [28]:
new_df = med[['index','Drug_Name','tags']]

In [29]:
new_df.head()

index                                          Drug_Name  \
0      1               A CN Gel(Topical) 20gmA CN Soap 75gm   
1      2  A Ret 0.05% Gel 20gmA Ret 0.1% Gel 20gmA Ret 0...   
2      3                             ACGEL CL NANO Gel 15gm   
3      4                                ACGEL NANO Gel 15gm   
4      5                              Acleen 1% Lotion 25ml   

                                                tags  
0          [Mild, to, moderate, acne, (spots), Acne]  
1  [A, RET, 0.025%, is, a, prescription, medicine...  
2  [It, is, used, to, treat, acne, vulgaris, in, ...  
3  [It, is, used, to, treat, acne, vulgaris, in, ...  
4  [treat, the, most, severe, form, of, acne, (no...

In [30]:
new_df['tags'].apply(lambda x:" ".join(x))

0                      Mild to moderate acne (spots) Acne
1       A RET 0.025% is a prescription medicine that i...
2       It is used to treat acne vulgaris in people 12...
3       It is used to treat acne vulgaris in people 12...
4       treat the most severe form of acne (nodular ac...
                              ...                        
9715                        used for treating warts Wound
9716                  used to soften the skin cells Wound
9717                                 used for scars Wound
9718                                used for wounds Wound
9719    used to treat and remove raised warts (usually...
Name: tags, Length: 9720, dtype: object

In [31]:
new_df

index                                          Drug_Name  \
0         1               A CN Gel(Topical) 20gmA CN Soap 75gm   
1         2  A Ret 0.05% Gel 20gmA Ret 0.1% Gel 20gmA Ret 0...   
2         3                             ACGEL CL NANO Gel 15gm   
3         4                                ACGEL NANO Gel 15gm   
4         5                              Acleen 1% Lotion 25ml   
...     ...                                                ...   
9715   9716                                T Muce Ointment 5gm   
9716   9717  Wokadine 10% Solution 100mlWokadine Solution 5...   
9717   9718                               Wokadine M Onit 10gm   
9718   9719                           Wound Fix Solution 100ml   
9719   9720                              Wounsol Ointment 15gm   

                                                   tags  
0             [Mild, to, moderate, acne, (spots), Acne]  
1     [A, RET, 0.025%, is, a, prescription, medicine...  
2     [It, is, used, to, treat, acne, vulgaris, in, ...  
3     [It, is, used, to, treat, acne, vulgaris, in, ...  
4     [treat, the, most, severe, form, of, acne, (no...  
...                                                 ...  
9715                [used, for, treating, warts, Wound]  
9716        [used, to, soften, the, skin, cells, Wound]  
9717                          [used, for, scars, Wound]  
9718                         [used, for, wounds, Wound]  
9719  [used, to, treat, and, remove, raised, warts, ...  

[9720 rows x 3 columns]

In [32]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

<ipython-input-32-ad44e9ca1347>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))


In [33]:
new_df

index                                          Drug_Name  \
0         1               A CN Gel(Topical) 20gmA CN Soap 75gm   
1         2  A Ret 0.05% Gel 20gmA Ret 0.1% Gel 20gmA Ret 0...   
2         3                             ACGEL CL NANO Gel 15gm   
3         4                                ACGEL NANO Gel 15gm   
4         5                              Acleen 1% Lotion 25ml   
...     ...                                                ...   
9715   9716                                T Muce Ointment 5gm   
9716   9717  Wokadine 10% Solution 100mlWokadine Solution 5...   
9717   9718                               Wokadine M Onit 10gm   
9718   9719                           Wound Fix Solution 100ml   
9719   9720                              Wounsol Ointment 15gm   

                                                   tags  
0                    Mild to moderate acne (spots) Acne  
1     A RET 0.025% is a prescription medicine that i...  
2     It is used to treat acne vulgaris in people 12...  
3     It is used to treat acne vulgaris in people 12...  
4     treat the most severe form of acne (nodular ac...  
...                                                 ...  
9715                      used for treating warts Wound  
9716                used to soften the skin cells Wound  
9717                               used for scars Wound  
9718                              used for wounds Wound  
9719  used to treat and remove raised warts (usually...  

[9720 rows x 3 columns]

In [34]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

<ipython-input-34-8b60b591a07f>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())


In [35]:
new_df

index                                          Drug_Name  \
0         1               A CN Gel(Topical) 20gmA CN Soap 75gm   
1         2  A Ret 0.05% Gel 20gmA Ret 0.1% Gel 20gmA Ret 0...   
2         3                             ACGEL CL NANO Gel 15gm   
3         4                                ACGEL NANO Gel 15gm   
4         5                              Acleen 1% Lotion 25ml   
...     ...                                                ...   
9715   9716                                T Muce Ointment 5gm   
9716   9717  Wokadine 10% Solution 100mlWokadine Solution 5...   
9717   9718                               Wokadine M Onit 10gm   
9718   9719                           Wound Fix Solution 100ml   
9719   9720                              Wounsol Ointment 15gm   

                                                   tags  
0                    mild to moderate acne (spots) acne  
1     a ret 0.025% is a prescription medicine that i...  
2     it is used to treat acne vulgaris in people 12...  
3     it is used to treat acne vulgaris in people 12...  
4     treat the most severe form of acne (nodular ac...  
...                                                 ...  
9715                      used for treating warts wound  
9716                used to soften the skin cells wound  
9717                               used for scars wound  
9718                              used for wounds wound  
9719  used to treat and remove raised warts (usually...  

[9720 rows x 3 columns]

In [36]:
!pip install nltk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [37]:
import nltk

In [38]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [39]:
!pip install -U scikit-learn scipy matplotlib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [40]:
from sklearn.feature_extraction.text import CountVectorizer


In [41]:
cv = CountVectorizer(stop_words='english',max_features=5000)

In [42]:
def stem(text):
  y = []

  for i in text.split():
    y.append(ps.stem(i))

  return " ".join(y)

In [43]:
new_df['tags'] = new_df['tags'].apply(stem)

<ipython-input-43-be18a4346d89>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)


In [44]:
cv.fit_transform(new_df['tags']).toarray().shape

(9720, 806)

In [45]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [48]:
from sklearn.feature_extraction.text import CountVectorizer

In [50]:
cv.get_feature_names_out()

array(['025', '12', '16', '18', 'abdomin', 'abl', 'ach', 'acid', 'acn',
       'acne', 'acquir', 'action', 'activ', 'acut', 'acute', 'adequ',
       'adhd', 'adjunct', 'adolesc', 'adult', 'adults', 'affect', 'ag',
       'age', 'aids', 'allerg', 'allergen', 'allergi', 'allow', 'alon',
       'alzheim', 'alzheimer', 'alzheimerâ', 'amoebiasi', 'anaemia',
       'anal', 'angina', 'angl', 'ani', 'ankylos', 'anorexia', 'anoth',
       'anti', 'antioxid', 'antipsychot', 'antiretrovir', 'anxieti',
       'anxiou', 'anxious', 'apnoea', 'appear', 'appetit', 'appetite',
       'appli', 'appropri', 'area', 'arrhythmia', 'arrhythmiasi',
       'arteri', 'arthralgia', 'arthriti', 'associ', 'atherothrombot',
       'athleteâ', 'atop', 'atrial', 'attack', 'awak', 'b1', 'b2', 'b3',
       'b5', 'b6', 'babi', 'backache', 'bacteri', 'bacteria', 'balanc',
       'balanitis', 'bandag', 'becom', 'behaviour', 'beliefs', 'benefit',
       'beta', 'biliari', 'biotin', 'bite', 'blackhead', 'blackheads',
      

In [52]:
from sklearn.metrics.pairwise import cosine_similarity

In [53]:
cosine_similarity(vectors)

array([[1.        , 0.25197632, 0.43643578, ..., 0.        , 0.        ,
        0.        ],
       [0.25197632, 1.        , 0.25660012, ..., 0.19245009, 0.1490712 ,
        0.0860663 ],
       [0.43643578, 0.25660012, 1.        , ..., 0.11111111, 0.0860663 ,
        0.0993808 ],
       ...,
       [0.        , 0.19245009, 0.11111111, ..., 1.        , 0.77459667,
        0.2981424 ],
       [0.        , 0.1490712 , 0.0860663 , ..., 0.77459667, 1.        ,
        0.34641016],
       [0.        , 0.0860663 , 0.0993808 , ..., 0.2981424 , 0.34641016,
        1.        ]])

In [54]:
similarity = cosine_similarity(vectors)

In [56]:
similarity[2]

array([0.43643578, 0.25660012, 1.        , ..., 0.11111111, 0.0860663 ,
       0.0993808 ])

In [57]:
similarity[1]

array([0.25197632, 1.        , 0.25660012, ..., 0.19245009, 0.1490712 ,
       0.0860663 ])

In [58]:
similarity[3]

array([0.43643578, 0.25660012, 1.        , ..., 0.11111111, 0.0860663 ,
       0.0993808 ])

In [59]:
def recommend(medicine):
    medicine_index = new_df[new_df['Drug_Name'] == medicine].index[0]
    distances = similarity[medicine_index]
    medicines_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in medicines_list:
        print(new_df.iloc[i[0]].Drug_Name)

In [63]:
import pickle

In [64]:
pickle.dump(new_df.to_dict(),open('medicine_dict.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))

In [65]:
recommend("Paracetamol 125mg Syrup 60mlParacetamol 500mg Tablet 10'S")

Oxypamol D Tablet 10'S
Pacimol MF Tablet 10'S
Painil Plus 100/500mg Tablet 10'S
Pamagin Plus Gel 30gm
Paracetamol 125mg Syrup 60mlParacetamol 500mg Tablet 10'S
